#ifndef GUARD_CONSTANTS_BATTLE_SETUP_H
#define GUARD_CONSTANTS_BATTLE_SETUP_H

enum TrainerBattles
{
    TRAINER_BATTLE_SINGLE,
    TRAINER_BATTLE_CONTINUE_SCRIPT_NO_MUSIC,
    TRAINER_BATTLE_CONTINUE_SCRIPT,
    TRAINER_BATTLE_SINGLE_NO_INTRO_TEXT,
    TRAINER_BATTLE_DOUBLE,
    TRAINER_BATTLE_REMATCH,
    TRAINER_BATTLE_CONTINUE_SCRIPT_DOUBLE,
    TRAINER_BATTLE_REMATCH_DOUBLE,
    TRAINER_BATTLE_CONTINUE_SCRIPT_DOUBLE_NO_MUSIC,
    TRAINER_BATTLE_SET_TRAINER,
};

#endif // GUARD_CONSTANTS_BATTLE_SETUP_H
