#ifndef GUARD_CONSTANTS_BATTLE_ANIM_H
#define GUARD_CONSTANTS_BATTLE_ANIM_H

#include "battle_anim_scripts.h"

enum AnimTags
{
    ANIM_TAG_BONE,
    ANIM_TAG_SPARK,
    ANIM_TAG_PENCIL,
    ANIM_TAG_AIR_WAVE,
    ANIM_TAG_ORB,
    ANIM_TAG_SWORD,
    ANIM_TAG_SEED,
    ANIM_TAG_EXPLOSION_6,
    ANIM_TAG_PINK_ORB, // unused
    ANIM_TAG_GUST,
    ANIM_TAG_ICE_CUBE,
    ANIM_TAG_SPARK_2,
    ANIM_TAG_ORANGE, // unused
    ANIM_TAG_YELLOW_BALL,
    ANIM_TAG_LOCK_ON,
    ANIM_TAG_TIED_BAG,
    ANIM_TAG_BLACK_SMOKE,
    ANIM_TAG_BLACK_BALL,
    ANIM_TAG_CONVERSION,
    ANIM_TAG_GLASS, // unused
    ANIM_TAG_HORN_HIT,
    ANIM_TAG_HIT,
    ANIM_TAG_HIT_2,
    ANIM_TAG_BLUE_SHARDS, // unused
    ANIM_TAG_CLOSING_EYE, // unused
    ANIM_TAG_WAVING_HAND, // unused
    ANIM_TAG_HIT_DUPLICATE, // unused
    ANIM_TAG_LEER,
    ANIM_TAG_BLUE_BURST, // unused
    ANIM_TAG_SMALL_EMBER,
    ANIM_TAG_GRAY_SMOKE,
    ANIM_TAG_BLUE_STAR,
    ANIM_TAG_BUBBLE_BURST,
    ANIM_TAG_FIRE,
    ANIM_TAG_SPINNING_FIRE, // unused
    ANIM_TAG_FIRE_PLUME,
    ANIM_TAG_LIGHTNING_2, // unused
    ANIM_TAG_LIGHTNING,
    ANIM_TAG_CLAW_SLASH_2, // unused
    ANIM_TAG_CLAW_SLASH,
    ANIM_TAG_SCRATCH_3, // unused
    ANIM_TAG_SCRATCH_2, // unused
    ANIM_TAG_BUBBLE_BURST_2, // unused
    ANIM_TAG_ICE_CHUNK,
    ANIM_TAG_GLASS_2, // unused
    ANIM_TAG_PINK_HEART_2, // unused
    ANIM_TAG_SAP_DRIP, // unused
    ANIM_TAG_SAP_DRIP_2, // unused
    ANIM_TAG_SPARKLE_1,
    ANIM_TAG_SPARKLE_2,
    ANIM_TAG_HUMANOID_FOOT,
    ANIM_TAG_MONSTER_FOOT,
    ANIM_TAG_HUMANOID_HAND, // unused
    ANIM_TAG_NOISE_LINE,
    ANIM_TAG_YELLOW_UNK, // unused
    ANIM_TAG_RED_FIST, // unused
    ANIM_TAG_SLAM_HIT,
    ANIM_TAG_RING, // unused
    ANIM_TAG_ROCKS,
    ANIM_TAG_Z, // unused
    ANIM_TAG_YELLOW_UNK_2, // unused
    ANIM_TAG_AIR_SLASH, // unused
    ANIM_TAG_SPINNING_GREEN_ORBS, // unused
    ANIM_TAG_LEAF,
    ANIM_TAG_FINGER,
    ANIM_TAG_POISON_POWDER,
    ANIM_TAG_BROWN_TRIANGLE, // unused
    ANIM_TAG_SLEEP_POWDER,
    ANIM_TAG_STUN_SPORE,
    ANIM_TAG_POWDER, // unused
    ANIM_TAG_SPARKLE_3,
    ANIM_TAG_SPARKLE_4,
    ANIM_TAG_MUSIC_NOTES,
    ANIM_TAG_DUCK,
    ANIM_TAG_MUD_SAND,
    ANIM_TAG_ALERT,
    ANIM_TAG_BLUE_FLAMES, // unused
    ANIM_TAG_BLUE_FLAMES_2, // unused
    ANIM_TAG_SHOCK_4, // unused
    ANIM_TAG_SHOCK,
    ANIM_TAG_BELL_2, // unused
    ANIM_TAG_PINK_GLOVE, // unused
    ANIM_TAG_BLUE_LINES, // unused
    ANIM_TAG_IMPACT_3, // unused
    ANIM_TAG_IMPACT_2, // unused
    ANIM_TAG_RETICLE, // unused
    ANIM_TAG_BREATH,
    ANIM_TAG_ANGER,
    ANIM_TAG_SNOWBALL, // unused
    ANIM_TAG_VINE, // unused
    ANIM_TAG_SWORD_2, // unused
    ANIM_TAG_CLAPPING, // unused
    ANIM_TAG_RED_TUBE, // unused
    ANIM_TAG_AMNESIA,
    ANIM_TAG_STRING_2, // unused
    ANIM_TAG_PENCIL_2, // unused
    ANIM_TAG_PETAL, // unused
    ANIM_TAG_BENT_SPOON,
    ANIM_TAG_WEB, // unused
    ANIM_TAG_MILK_BOTTLE,
    ANIM_TAG_COIN,
    ANIM_TAG_CRACKED_EGG, // unused
    ANIM_TAG_HATCHED_EGG, // unused
    ANIM_TAG_FRESH_EGG, // unused
    ANIM_TAG_FANGS, // unused
    ANIM_TAG_EXPLOSION_2, // unused
    ANIM_TAG_EXPLOSION_3, // unused
    ANIM_TAG_WATER_DROPLET, // unused
    ANIM_TAG_WATER_DROPLET_2, // unused
    ANIM_TAG_SEED_2, // unused
    ANIM_TAG_SPROUT, // unused
    ANIM_TAG_RED_WAND, // unused
    ANIM_TAG_PURPLE_GREEN_UNK, // unused
    ANIM_TAG_WATER_COLUMN, // unused
    ANIM_TAG_MUD_UNK, // unused
    ANIM_TAG_RAIN_DROPS,
    ANIM_TAG_FURY_SWIPES, // unused
    ANIM_TAG_VINE_2, // unused
    ANIM_TAG_TEETH, // unused
    ANIM_TAG_BONE_2, // unused
    ANIM_TAG_WHITE_BAG, // unused
    ANIM_TAG_PURPLE_CORAL, // unused
    ANIM_TAG_PURPLE_DROPLET, // unused
    ANIM_TAG_SHOCK_2, // unused
    ANIM_TAG_CLOSING_EYE_2, // unused
    ANIM_TAG_METAL_BALL, // unused
    ANIM_TAG_MONSTER_DOLL, // unused
    ANIM_TAG_WHIRLWIND, // unused
    ANIM_TAG_WHIRLWIND_2, // unused
    ANIM_TAG_EXPLOSION_4, // unused
    ANIM_TAG_EXPLOSION_5, // unused
    ANIM_TAG_TONGUE, // unused
    ANIM_TAG_SMOKE, // unused
    ANIM_TAG_SMOKE_2, // unused
    ANIM_TAG_IMPACT,
    ANIM_TAG_CIRCLE_IMPACT,
    ANIM_TAG_SCRATCH,
    ANIM_TAG_CUT,
    ANIM_TAG_SHARP_TEETH,
    ANIM_TAG_RAINBOW_RINGS,
    ANIM_TAG_ICE_CRYSTALS,
    ANIM_TAG_ICE_SPIKES,
    ANIM_TAG_HANDS_AND_FEET,
    ANIM_TAG_MIST_CLOUD,
    ANIM_TAG_CLAMP,
    ANIM_TAG_BUBBLE,
    ANIM_TAG_ORBS,
    ANIM_TAG_WATER_IMPACT,
    ANIM_TAG_WATER_ORB,
    ANIM_TAG_POISON_BUBBLE,
    ANIM_TAG_TOXIC_BUBBLE,
    ANIM_TAG_SPIKES,
    ANIM_TAG_HORN_HIT_2,
    ANIM_TAG_AIR_WAVE_2,
    ANIM_TAG_SMALL_BUBBLES,
    ANIM_TAG_ROUND_SHADOW,
    ANIM_TAG_SUNLIGHT,
    ANIM_TAG_SPORE,
    ANIM_TAG_FLOWER,
    ANIM_TAG_RAZOR_LEAF,
    ANIM_TAG_NEEDLE,
    ANIM_TAG_WHIRLWIND_LINES,
    ANIM_TAG_GOLD_RING,
    ANIM_TAG_PURPLE_RING,
    ANIM_TAG_BLUE_RING,
    ANIM_TAG_GREEN_LIGHT_WALL,
    ANIM_TAG_BLUE_LIGHT_WALL,
    ANIM_TAG_RED_LIGHT_WALL,
    ANIM_TAG_GRAY_LIGHT_WALL,
    ANIM_TAG_ORANGE_LIGHT_WALL,
    ANIM_TAG_BLACK_BALL_2,
    ANIM_TAG_PURPLE_GAS_CLOUD,
    ANIM_TAG_SPARK_H,
    ANIM_TAG_YELLOW_STAR,
    ANIM_TAG_LARGE_FRESH_EGG,
    ANIM_TAG_SHADOW_BALL,
    ANIM_TAG_LICK,
    ANIM_TAG_VOID_LINES,
    ANIM_TAG_STRING,
    ANIM_TAG_WEB_THREAD,
    ANIM_TAG_SPIDER_WEB,
    ANIM_TAG_LIGHTBULB, // unused
    ANIM_TAG_SLASH,
    ANIM_TAG_FOCUS_ENERGY,
    ANIM_TAG_SPHERE_TO_CUBE,
    ANIM_TAG_TENDRILS,
    ANIM_TAG_EYE,
    ANIM_TAG_WHITE_SHADOW,
    ANIM_TAG_TEAL_ALERT,
    ANIM_TAG_OPENING_EYE,
    ANIM_TAG_ROUND_WHITE_HALO,
    ANIM_TAG_FANG_ATTACK,
    ANIM_TAG_PURPLE_HAND_OUTLINE,
    ANIM_TAG_MOON,
    ANIM_TAG_GREEN_SPARKLE,
    ANIM_TAG_SPIRAL,
    ANIM_TAG_SNORE_Z,
    ANIM_TAG_EXPLOSION,
    ANIM_TAG_NAIL,
    ANIM_TAG_GHOSTLY_SPIRIT,
    ANIM_TAG_WARM_ROCK,
    ANIM_TAG_BREAKING_EGG,
    ANIM_TAG_THIN_RING,
    ANIM_TAG_PUNCH_IMPACT, // unused
    ANIM_TAG_BELL,
    ANIM_TAG_MUSIC_NOTES_2,
    ANIM_TAG_SPEED_DUST,
    ANIM_TAG_TORN_METAL,
    ANIM_TAG_THOUGHT_BUBBLE,
    ANIM_TAG_MAGENTA_HEART,
    ANIM_TAG_ELECTRIC_ORBS,
    ANIM_TAG_CIRCLE_OF_LIGHT,
    ANIM_TAG_ELECTRICITY,
    ANIM_TAG_FINGER_2,
    ANIM_TAG_MOVEMENT_WAVES,
    ANIM_TAG_RED_HEART,
    ANIM_TAG_RED_ORB,
    ANIM_TAG_EYE_SPARKLE,
    ANIM_TAG_PINK_HEART,
    ANIM_TAG_ANGEL,
    ANIM_TAG_DEVIL,
    ANIM_TAG_SWIPE,
    ANIM_TAG_ROOTS,
    ANIM_TAG_ITEM_BAG,
    ANIM_TAG_JAGGED_MUSIC_NOTE,
    ANIM_TAG_POKEBALL,
    ANIM_TAG_SPOTLIGHT,
    ANIM_TAG_LETTER_Z,
    ANIM_TAG_GIRO_RAPIDO,
    ANIM_TAG_TRI_ATTACK_TRIANGLE,
    ANIM_TAG_WISP_ORB,
    ANIM_TAG_WISP_FIRE,
    ANIM_TAG_GOLD_STARS,
    ANIM_TAG_ECLIPSING_ORB,
    ANIM_TAG_GRAY_ORB,
    ANIM_TAG_BLUE_ORB,
    ANIM_TAG_RED_ORB_2,
    ANIM_TAG_PINK_PETAL,
    ANIM_TAG_PAIN_SPLIT,
    ANIM_TAG_CONFETTI,
    ANIM_TAG_GREEN_STAR,
    ANIM_TAG_PINK_CLOUD,
    ANIM_TAG_SWEAT_DROP,
    ANIM_TAG_GUARD_RING,
    ANIM_TAG_PURPLE_SCRATCH,
    ANIM_TAG_PURPLE_SWIPE,
    ANIM_TAG_TAG_HAND,
    ANIM_TAG_SMALL_RED_EYE,
    ANIM_TAG_HOLLOW_ORB,
    ANIM_TAG_X_SIGN,
    ANIM_TAG_BLUEGREEN_ORB,
    ANIM_TAG_PAW_PRINT,
    ANIM_TAG_PURPLE_FLAME,
    ANIM_TAG_RED_BALL,
    ANIM_TAG_SMELLINGSALT_EFFECT,
    ANIM_TAG_METEOR,
    ANIM_TAG_FLAT_ROCK,
    ANIM_TAG_MAGNIFYING_GLASS,
    ANIM_TAG_BROWN_ORB,
    ANIM_TAG_METAL_SOUND_WAVES,
    ANIM_TAG_FLYING_DIRT,
    ANIM_TAG_ICICLE_SPEAR,
    ANIM_TAG_HAIL,
    ANIM_TAG_GLOWY_RED_ORB,
    ANIM_TAG_GLOWY_GREEN_ORB,
    ANIM_TAG_GREEN_SPIKE,
    ANIM_TAG_WHITE_CIRCLE_OF_LIGHT,
    ANIM_TAG_GLOWY_BLUE_ORB,
    ANIM_TAG_POKEBLOCK,
    ANIM_TAG_WHITE_FEATHER,
    ANIM_TAG_SPARKLE_6,
    ANIM_TAG_SPLASH,
    ANIM_TAG_SWEAT_BEAD,
    ANIM_TAG_GEM_1, // unused
    ANIM_TAG_GEM_2, // unused
    ANIM_TAG_GEM_3, // unused
    ANIM_TAG_SLAM_HIT_2,
    ANIM_TAG_RECYCLE,
    ANIM_TAG_RED_PARTICLES, // unused
    ANIM_TAG_PROTECT,
    ANIM_TAG_DIRT_MOUND,
    ANIM_TAG_SHOCK_3,
    ANIM_TAG_WEATHER_BALL,
    ANIM_TAG_BIRD,
    ANIM_TAG_CROSS_IMPACT,
    ANIM_TAG_SLASH_2,
    ANIM_TAG_WHIP_HIT,
    ANIM_TAG_BLUE_RING_2,
    ANIM_TAG_WHITE_STREAK,
    ANIM_TAG_PURPLE_JAB,
    ANIM_TAG_TOXIC_SPIKES,
    ANIM_TAG_ENERGY_BALL,
    ANIM_TAG_SEED_BROWN,
    ANIM_TAG_FEINT,
    ANIM_TAG_TRUMP_CARD,
    ANIM_TAG_TRUMP_CARD_PARTICLES,
    ANIM_TAG_ACUPRESSURE,
    ANIM_TAG_WRING_OUT,
    ANIM_TAG_COLORED_ORBS,
    ANIM_TAG_SMALL_CLOUD,
    ANIM_TAG_ATTACK_ORDER,
    ANIM_TAG_DRAGON_PULSE,
    ANIM_TAG_WOOD_HAMMER,
    ANIM_TAG_PSYCHO_CUT,
    ANIM_TAG_POWER_GEM,
    ANIM_TAG_STONE_EDGE,
    ANIM_TAG_STEALTH_ROCK,
    ANIM_TAG_POISON_JAB,
    ANIM_TAG_GREEN_POISON_BUBBLE,
    ANIM_TAG_FLASH_CANNON_BALL,
    ANIM_TAG_WATER_GUN,
    ANIM_TAG_PUNISHMENT_BLADES,
    ANIM_TAG_QUICK_GUARD_HAND,
    ANIM_TAG_SHELL_RIGHT,
    ANIM_TAG_SHELL_LEFT,
    ANIM_TAG_RAZOR_SHELL,
    ANIM_TAG_HYDRO_PUMP,
    ANIM_TAG_BRINE,
    ANIM_TAG_GEAR,
    ANIM_TAG_ASSURANCE_HAND,
    ANIM_TAG_WISHIWASHI_FISH,
    ANIM_TAG_ZYGARDE_HEXES,
    ANIM_TAG_AURA_SPHERE,
    ANIM_TAG_BERRY_NORMAL,
    ANIM_TAG_BERRY_EATEN,
    ANIM_TAG_DRAGON_ASCENT,
    ANIM_TAG_PINK_DIAMOND,
    ANIM_TAG_STEAM_ERUPTION,
    ANIM_TAG_CONFIDE,
    ANIM_TAG_VERTICAL_HEX,
    ANIM_TAG_ASCUAS,
    ANIM_TAG_POWER_TRICK,
    ANIM_TAG_CHAIN_LINK,
    ANIM_TAG_ANCHOR,
    ANIM_TAG_HORSESHOE_SIDE_FIST,
    ANIM_TAG_DRAGON_ASCENT_FOE,
    ANIM_TAG_CRAFTY_SHIELD,
    ANIM_TAG_BLACEPHALON_HEAD,
    ANIM_TAG_FAIRY_LOCK_CHAINS,
    ANIM_TAG_IONS,
    ANIM_TAG_CHOP,
    ANIM_TAG_HORN_LEECH,
    ANIM_TAG_RODILLO,
    ANIM_TAG_HOOPA_HAND,
    ANIM_TAG_HOOPA_RING,
    ANIM_TAG_METAL_BITS,
    ANIM_TAG_SMALL_ROCK,
    ANIM_TAG_SPIRIT_ARROW,
    ANIM_TAG_REALLY_BIG_ROCK,
    ANIM_TAG_COCOON,
    ANIM_TAG_CORKSCREW,
    ANIM_TAG_HAVOC_SPEAR,
    ANIM_TAG_PURPLE_DRAKE,
    ANIM_TAG_MUD_BOMB,
    ANIM_TAG_BRANCH,
    ANIM_TAG_APPLE,
    ANIM_TAG_OBSTRUCT_CROSS,
    ANIM_TAG_POISON_COLUMN,
    ANIM_TAG_GARBAGE_COLUMN,
    ANIM_TAG_LARGE_SPIKE,
    ANIM_TAG_DRAGON_PULSE_RING,
    ANIM_TAG_STONE_PILLAR,
    ANIM_TAG_MUSHROOM,
    ANIM_TAG_GOLDEN_APPLE,
    ANIM_TAG_ICE_ROCK,
    ANIM_TAG_TORNADO,
    ANIM_TAG_STRAIGHT_BEAM,
    ANIM_TAG_DREEPY,
    ANIM_TAG_ICE_ROCK_SINGLE,
    ANIM_TAG_STONE_PILLAR_MULTI,
    ANIM_TAG_STEEL_BEAM,
    ANIM_TAG_POLTERGEIST,
    ANIM_TAG_TEAPOT,
    ANIM_TAG_WOOD_HAMMER_HAMMER,
    ANIM_TAG_SNOWFLAKES,
    ANIM_TAG_DREEPY_SHINY,
    ANIM_TAG_BLOOD_MOON,
    ANIM_TAG_BEAM,
    ANIM_TAG_RED_EXPLOSION,
    ANIM_TAG_PURPLE_CHAIN,
    ANIM_TAG_PINKVIO_ORB,

    ANIM_TAG_COUNT
};

#define TAG_MUSIC_NOTES_TEMP_BASE 0xF000
#define TAG_VS_LETTER             0xEFFF

// battlers
#define ANIM_ATTACKER         0
#define ANIM_TARGET           1
#define ANIM_ATK_PARTNER      2
#define ANIM_DEF_PARTNER      3

// Below are used by AnimTask_ShakeMon2 and AnimTask_SetGrayscaleOrOriginalPal
#define ANIM_PLAYER_LEFT      (NUMERO_COMBATIENTES + 0)
#define ANIM_OPPONENT_LEFT    (NUMERO_COMBATIENTES + 1)
#define ANIM_PLAYER_RIGHT     (NUMERO_COMBATIENTES + 2)
#define ANIM_OPPONENT_RIGHT   (NUMERO_COMBATIENTES + 3)
#define ANIM_ATTACKER_FORCE   (NUMERO_COMBATIENTES + 4)

// stereo panning constants [0-255]
//
//          0
//         .  .
//      .        .
// 192 .          . 63
//     .          .
//      .        .
//         .  .
//          127
//
#define SOUND_PAN_ATTACKER -64
#define SOUND_PAN_TARGET    63

enum BgMovimientos
{
    BG_DARK,
    BG_GHOST,
    BG_PSYCHIC,
    BG_IMPACT_OPPONENT,
    BG_IMPACT_PLAYER,
    BG_DRILL,
    BG_DRILL_CONTESTS,
    BG_HIGHSPEED_OPPONENT,
    BG_HIGHSPEED_PLAYER,
    BG_THUNDER,
    BG_GUILLOTINE_OPPONENT,
    BG_GUILLOTINE_PLAYER,
    BG_GUILLOTINE_CONTESTS,
    BG_ICE,
    BG_COSMIC,
    BG_IN_AIR,
    BG_SKY,
    BG_SKY_CONTESTS,
    BG_AURORA,
    BG_FISSURE,
    BG_BUG_OPPONENT,
    BG_BUG_PLAYER,
    BG_SOLAR_BEAM_OPPONENT,
    BG_SOLAR_BEAM_PLAYER,
    BG_SOLAR_BEAM_CONTESTS,
    BG_MAGMA_STORM,
    BG_GIGA_IMPACT_OPPONENT,
    BG_GIGA_IMPACT_PLAYER,
    BG_GIGA_IMPACT_CONTEST,
    BG_TRICK_ROOM,
    BG_ROCK_WRECKER,
    BG_SPACIAL_REND_ON_OPPONENT,
    BG_SPACIAL_REND_ON_PLAYER,
    BG_DARK_VOID,
    BG_WATER,
    BG_NIGHTMARE,
    BG_LEAF_STORM,
    BG_FIRE,
    BG_FIRE_2,
    BG_WATER_2,
    BG_POISON,
    BG_AEROBLAST,
    BG_HURRICANE,
    BG_FOCUS_BLAST,
    BG_GUNK_SHOT,
    BG_HYDRO_CANNON,
    BG_WONDER_ROOM,
    BG_MAGIC_ROOM,
    BG_HYPERSPACE_FURY,
    BG_BOLT_STRIKE,
    BG_TECTONIC_RAGE,
    BG_BLUE_SKY_DAY,
    BG_BLUE_SKY_AFTERNOON,
    BG_BLUE_SKY_NIGHT,
    BG_NEVERENDING_NIGHTMARE,
    BG_WATER_PULSE,
    BG_INFERNO_OVERDRIVE,
    BG_BLOOM_DOOM,
    BG_SHATTERED_PSYCHE,
    BG_TWINKLE_TACKLE,
    BG_BLACKHOLE_ECLIPSE,
    BG_MALICIOUS_MOONSAULT,
    BG_SNUGGLE_FOREVER,
    BG_MAX_LIGHTNING,
    BG_GARBAGE_FALLS,
    BG_HYPER_BEAM,
    BG_AURA_SPHERE,
    BG_STEEL_BEAM_OPPONENT,
    BG_STEEL_BEAM_PLAYER,
    BG_CHLOROBLAST,
};

enum AnimacionesGeneralesBatalla //(sBattleAnims_General)
{
    B_ANIM_STATS_CHANGE,
    B_ANIM_SUBSTITUTE_FADE,
    B_ANIM_SUBSTITUTE_APPEAR,
    B_ANIM_POKEBLOCK_THROW,
    B_ANIM_ITEM_KNOCKOFF,
    B_ANIM_TURN_TRAP,
    B_ANIM_HELD_ITEM_EFFECT,
    B_ANIM_SMOKEBALL_ESCAPE,
    B_ANIM_RAIN_CONTINUES,
    B_ANIM_SUN_CONTINUES,
    B_ANIM_SANDSTORM_CONTINUES,
    B_ANIM_HAIL_CONTINUES,
    B_ANIM_LEECH_SEED_DRAIN,
    B_ANIM_MON_HIT,
    B_ANIM_ITEM_STEAL,
    B_ANIM_SNATCH_MOVE,
    B_ANIM_FUTURE_SIGHT_HIT,
    B_ANIM_DOOM_DESIRE_HIT,
    B_ANIM_FOCUS_PUNCH_SETUP,
    B_ANIM_INGRAIN_HEAL,
    B_ANIM_WISH_HEAL,
    B_ANIM_FORM_CHANGE,
    B_ANIM_SLIDE_OFFSCREEN, // Sin usar
    B_ANIM_RESTORE_BG, // for Terrain Endings
    B_ANIM_AQUA_RING_HEAL,
    B_ANIM_SNOW_CONTINUES,
    B_ANIM_TRICK_ROOM,
    B_ANIM_WONDER_ROOM,
    B_ANIM_MAGIC_ROOM,
    B_ANIM_TAILWIND,
    B_ANIM_FOG_CONTINUES,
    B_ANIM_SIMPLE_HEAL,

    NUM_B_ANIMS_GENERAL
};

enum AnimacionesEspecialesBatalla //(sBattleAnims_Special)
{
    B_ANIM_LVL_UP,
    B_ANIM_SWITCH_OUT_PLAYER_MON,
    B_ANIM_SWITCH_OUT_OPPONENT_MON,
    B_ANIM_BALL_THROW,
    B_ANIM_BALL_THROW_WITH_TRAINER,
    B_ANIM_SUBSTITUTE_TO_MON,
    B_ANIM_MON_TO_SUBSTITUTE,

    NUM_B_ANIMS_SPECIAL
};

// status animation table (sBattleAnims_StatusConditions)
#define B_ANIM_STATUS_PSN               0
#define B_ANIM_STATUS_CONFUSION         1
#define B_ANIM_STATUS_BRN               2
#define B_ANIM_STATUS_INFATUATION       3
#define B_ANIM_STATUS_SLP               4
#define B_ANIM_STATUS_PRZ               5
#define B_ANIM_STATUS_FRZ               6
#define B_ANIM_STATUS_CURSED            7
#define B_ANIM_STATUS_NIGHTMARE         8
#define NUM_B_ANIMS_STATUS              9

// Tasks with return values often assign them to gBattleAnimArgs[7].
#define ARG_RET_ID 7

// For createsprite macro to use internally
#define ANIMSPRITE_IS_TARGET (1 << 7)

// Trapping Wrap-like moves end turn animation.
#define TRAP_ANIM_BIND 0
#define TRAP_ANIM_WRAP 0
#define TRAP_ANIM_FIRE_SPIN 1
#define TRAP_ANIM_WHIRLPOOL 2
#define TRAP_ANIM_CLAMP 3
#define TRAP_ANIM_SAND_TOMB 4
#define TRAP_ANIM_MAGMA_STORM 5
#define TRAP_ANIM_INFESTATION 6
#define TRAP_ANIM_SNAP_TRAP 7
#define TRAP_ANIM_THUNDER_CAGE 8

// Weather defines for battle animation scripts.
#define ANIM_WEATHER_NONE 0
#define ANIM_WEATHER_SUN 1
#define ANIM_WEATHER_RAIN 2
#define ANIM_WEATHER_SANDSTORM 3
#define ANIM_WEATHER_HAIL 4
#define ANIM_WEATHER_SNOW 5
#define ANIM_WEATHER_FOG 6

// horseshoe/fist frames
#define ANIM_RIGHT_FIST  0
#define ANIM_LEFT_FIST   2

// fist/chop frames
#define ANIM_FIST_1  0
#define ANIM_FOOT_1  1
#define ANIM_FOOT_2  2
#define ANIM_CHOP    3

// surf wave palettes
#define ANIM_SURF_PAL_SURF           0
#define ANIM_SURF_PAL_MUDDY_WATER    1
#define ANIM_SURF_PAL_SLUDGE_WAVE    2

// Flags given to various functions to indicate which palettes to consider.
// Handled by UnpackSelectedBattlePalettes
#define F_PAL_BG                  (1 << 0)
#define F_PAL_ATTACKER            (1 << 1)
#define F_PAL_TARGET              (1 << 2)
#define F_PAL_ATK_PARTNER         (1 << 3)
#define F_PAL_DEF_PARTNER         (1 << 4)
#define F_PAL_ANIM_1              (1 << 5) // Palette set for GetBattleAnimBg1Data/GetBgDataForTransform. Only used (ineffectually?) by Aromatherapy.
#define F_PAL_ANIM_2              (1 << 6) // Palette set for GetBattleAnimBgData/GetBgDataForTransform. Unused.
#define F_PAL_ATK_SIDE            (F_PAL_ATTACKER | F_PAL_ATK_PARTNER)
#define F_PAL_DEF_SIDE            (F_PAL_TARGET | F_PAL_DEF_PARTNER)
#define F_PAL_BATTLERS            (F_PAL_ATK_SIDE | F_PAL_DEF_SIDE)
#define F_PAL_ADJACENT            (F_PAL_DEF_SIDE | F_PAL_ATK_PARTNER)
#define F_PAL_ALL_BUT_DEF         (F_PAL_ATK_SIDE | F_PAL_DEF_PARTNER)
#define F_PAL_ALL_BUT_ATK_PARTNER (F_PAL_ATTACKER | F_PAL_DEF_SIDE)
// The below are only used by AnimTask_BlendBattleAnimPal to get battler sprite palettes by position rather than by role.
// It's redundant with F_PAL_BATTLERS, because they're only ever used together to refer to all the battlers at once.
#define F_PAL_BATTLERS_2  (1 << 7 | 1 << 8 | 1 << 9 | 1 << 10)

#endif // GUARD_CONSTANTS_BATTLE_ANIM_H
