#ifndef GUARD_CONSTANTS_BATTLE_ANIM_SCRIPTS_H
#define GUARD_CONSTANTS_BATTLE_ANIM_SCRIPTS_H

// shell smash
#define SHELL_SMASH_STARTING_X              40
#define SHELL_SMASH_MOVEMENT_DISTANCE       34
#define SHELL_SMASH_SHELL_MOVE_IN_DURATION  16
#define SHELL_SMASH_PAUSE_DURATION          48

// thunder cage
#define THUNDER_CAGE_BALL_TIME  0x64

// mysitcal power
#define MYSTICAL_POWER_RING_PAUSE   7

// esper wing
#define ESPER_WING_SPEED    16

// triple arrows
#define TRIPLE_ARROW_FLY_TIME   9

#endif // GUARD_CONSTANTS_BATTLE_ANIM_SCRIPTS_H
