#ifndef GUARD_FIELD_EFFECT_CONSTANTS_H
#define GUARD_FIELD_EFFECT_CONSTANTS_H

// Los efectos de campo. La posicion es la id: los scripts de mapa lanzan por
// numero con dofieldeffect, y FieldEffectActiveListContains espera por id.
//
// Se fueron ocho que no hacian nada -restos de las bases secretas- y que
// ademas no referenciaba nadie.
enum EfectosDeCampo
{
    FLDEFF_EXCLAMATION_MARK_ICON,
    FLDEFF_USE_CUT_ON_GRASS,
    FLDEFF_USE_CUT_ON_TREE,
    FLDEFF_SHADOW,
    FLDEFF_TALL_GRASS,
    FLDEFF_RIPPLE,
    FLDEFF_FIELD_MOVE_SHOW_MON,
    FLDEFF_ASH,
    FLDEFF_USE_SURF,
    FLDEFF_DUST,
    FLDEFF_JUMP_TALL_GRASS,
    FLDEFF_SAND_FOOTPRINTS,
    FLDEFF_JUMP_BIG_SPLASH,
    FLDEFF_SPLASH,
    FLDEFF_JUMP_SMALL_SPLASH,
    FLDEFF_LONG_GRASS,
    FLDEFF_JUMP_LONG_GRASS,
    FLDEFF_WATER_SURFACING,
    FLDEFF_BERRY_TREE_GROWTH_SPARKLE,
    FLDEFF_DEEP_SAND_FOOTPRINTS,
    FLDEFF_POKECENTER_HEAL,
    FLDEFF_NPCFLY_OUT,
    FLDEFF_USE_FLY,
    FLDEFF_FLY_IN,
    FLDEFF_QUESTION_MARK_ICON,
    FLDEFF_FEET_IN_FLOWING_WATER,
    FLDEFF_BIKE_TIRE_TRACKS,
    FLDEFF_SAND_DISGUISE,
    FLDEFF_USE_ROCK_SMASH,
    FLDEFF_USE_DIG,
    FLDEFF_SAND_PILE,
    FLDEFF_USE_STRENGTH,
    FLDEFF_SHORT_GRASS,
    FLDEFF_HOT_SPRINGS_WATER,
    FLDEFF_USE_WATERFALL,
    FLDEFF_USE_DIVE,
    FLDEFF_POKEBALL_TRAIL,
    FLDEFF_HEART_ICON,
    FLDEFF_ASH_PUFF,
    FLDEFF_ASH_LAUNCH,
    FLDEFF_BUBBLES,
    FLDEFF_SPARKLE,
    FLDEFF_CUT_GRASS,
    FLDEFF_FIELD_MOVE_SHOW_MON_INIT,
    FLDEFF_HALL_OF_FAME_RECORD,
    FLDEFF_USE_TELEPORT,
    FLDEFF_RAYQUAZA_SPOTLIGHT,
    FLDEFF_DESTROY_DEOXYS_ROCK,
    FLDEFF_MOVE_DEOXYS_ROCK,
    FLDEFF_USE_VS_SEEKER,
    FLDEFF_X_ICON,
    FLDEFF_DOUBLE_EXCL_MARK_ICON,
    FLDEFF_TRACKS_SLITHER,
    FLDEFF_TRACKS_BUG,
    FLDEFF_TRACKS_SPOT,
    NUMERO_EFECTOS_CAMPO,
};

// Mismo efecto y misma ranura: el icono de interrogacion es el que se usa
// para las emociones de los personajes.
#define FLDEFF_EMOTE FLDEFF_QUESTION_MARK_ICON

#define FLDEFFOBJ_SHADOW_S              0
#define FLDEFFOBJ_SHADOW_M              1
#define FLDEFFOBJ_SHADOW_L              2
#define FLDEFFOBJ_SHADOW_XL             3
#define FLDEFFOBJ_TALL_GRASS            4
#define FLDEFFOBJ_RIPPLE                5
#define FLDEFFOBJ_ASH                   6
#define FLDEFFOBJ_ARROW                 8
#define FLDEFFOBJ_GROUND_IMPACT_DUST    9
#define FLDEFFOBJ_JUMP_TALL_GRASS       10
#define FLDEFFOBJ_SAND_FOOTPRINTS       11
#define FLDEFFOBJ_JUMP_BIG_SPLASH       12
#define FLDEFFOBJ_SPLASH                13
#define FLDEFFOBJ_JUMP_SMALL_SPLASH     14
#define FLDEFFOBJ_LONG_GRASS            15
#define FLDEFFOBJ_JUMP_LONG_GRASS       16
#define FLDEFFOBJ_WATER_SURFACING       17
#define FLDEFFOBJ_REFLECTION_DISTORTION 18
#define FLDEFFOBJ_SPARKLE               19
#define FLDEFFOBJ_DEEP_SAND_FOOTPRINTS  20
#define FLDEFFOBJ_TREE_DISGUISE         21
#define FLDEFFOBJ_MOUNTAIN_DISGUISE     22
#define FLDEFFOBJ_BIRD                  23
#define FLDEFFOBJ_BIKE_TIRE_TRACKS      24
#define FLDEFFOBJ_SAND_DISGUISE         25
#define FLDEFFOBJ_SAND_PILE             26
#define FLDEFFOBJ_SHORT_GRASS           27
#define FLDEFFOBJ_HOT_SPRINGS_WATER     28
#define FLDEFFOBJ_ASH_PUFF              29
#define FLDEFFOBJ_ASH_LAUNCH            30
#define FLDEFFOBJ_BUBBLES               31
#define FLDEFFOBJ_SMALL_SPARKLE         32
#define FLDEFFOBJ_RAYQUAZA              33
#define FLDEFFOBJ_TRACKS_SLITHER        34
#define FLDEFFOBJ_TRACKS_SPOT           35
#define FLDEFFOBJ_TRACKS_BUG            36

#define FLDEFF_PAL_TAG_CUT_GRASS          0x1000
#define FLDEFF_PAL_TAG_SECRET_POWER_TREE  0x1003
#define FLDEFF_PAL_TAG_GENERAL_0          0x1004
#define FLDEFF_PAL_TAG_GENERAL_1          0x1005
#define FLDEFF_PAL_TAG_POKEBALL_GLOW      0x1007
#define FLDEFF_PAL_TAG_SECRET_POWER_PLANT 0x1008
#define FLDEFF_PAL_TAG_POKEBALL_TRAIL     0x1009
#define FLDEFF_PAL_TAG_ASH                0x100D
#define FLDEFF_PAL_TAG_SAND_PILLAR        0x100E
#define FLDEFF_PAL_TAG_SMALL_SPARKLE      0x100F
#define FLDEFF_PAL_TAG_HOF_MONITOR        0x1010
#define FLDEFF_PAL_TAG_FIELD_MOVE_MON     0x8400

// tile tags, for field effects that may have many copies on screen at once
#define FLDEFF_TILE_TAG_SHADOW_SMALL        0x1400
#define FLDEFF_TILE_TAG_SHADOW_MEDIUM       0x1401
#define FLDEFF_TILE_TAG_SHADOW_LARGE        0x1402
#define FLDEFF_TILE_TAG_SHADOW_EXTRA_LARGE  0x1403

#endif // GUARD_FIELD_EFFECT_CONSTANTS_H
