#ifndef GUARD_CONSTANTS_FLAGS_H
#define GUARD_CONSTANTS_FLAGS_H

#include "constants/opponents.h"

// Las banderas son BITS dentro del bloque de guardado, no variables: todas juntas
// ocupan FLAGS_COUNT/8 bytes. Por eso el array es de u8 y no de u32: el bloque vive
// en EWRAM, que tiene bus de 16 bits, y una lectura de 32 costaria dos accesos donde
// ahora basta uno.
//
// El numero de cada bandera ES su posicion en ese bloque. Con enums el numero lo
// pone el compilador, que es comodo, pero tiene una consecuencia: anadir una en
// medio desplaza todas las siguientes e invalida las partidas guardadas. Mientras
// esto siga en desarrollo da igual. Cuando publiques, las nuevas van AL FINAL de su
// enum.
//
// Las de entrenador no estan aqui: tienen su propio array (trainerFlags) y se
// indexan por identificador de entrenador, no por nombre.

// Se borran al cargar cualquier mapa. Van juntas y al principio porque el borrado
// es por rango. La 0 no se usa: FlagGet la trata como "sin bandera".
enum BanderasTemporales
{
    FLAG_TEMP_NINGUNA = 0,
    FLAG_TEMP_1,
    FLAG_TEMP_HIDE_FOLLOWER,
    TEMP_FLAGS_END,
};

#define TEMP_FLAGS_START   (FLAG_TEMP_NINGUNA + 1)
#define NUM_TEMP_FLAGS     (TEMP_FLAGS_END - TEMP_FLAGS_START)

// Permanentes: progreso, sucesos del mundo y objetos ya recogidos.
enum BanderasGuion
{
    FLAG_RESCUED_BIRCH = TEMP_FLAGS_END + 1,
    FLAG_RECEIVED_BIKE,
    FLAG_WHITEOUT_TO_LAVARIDGE,
    FLAG_ADVENTURE_STARTED,
    FLAG_DEFEATED_MAGMA_SPACE_CENTER,
    FLAG_ENABLE_ROXANNE_FIRST_CALL,
    FLAG_PENDING_DAYCARE_EGG,
    FLAG_ENABLE_FIRST_WALLY_POKENAV_CALL,
    FLAG_SCOTT_CALL_FORTREE_GYM,
    FLAG_FORCE_MIRAGE_TOWER_VISIBLE,
    FLAG_RECEIVED_RUNNING_SHOES,
    FLAG_RECEIVED_SS_TICKET,
    FLAG_PETALBURG_MART_EXPANDED_ITEMS,
    FLAG_RECEIVED_BELDUM,
    FLAG_MIRAGE_TOWER_VISIBLE,
    FLAG_DEFEATED_DEOXYS,
    FLAG_SHOWN_EON_TICKET,
    FLAG_SHOWN_OLD_SEA_MAP,
    FLAG_DEFEATED_KYOGRE,
    FLAG_DEFEATED_GROUDON,
    FLAG_DEFEATED_MEW,
    FLAG_DEFEATED_LATIAS_OR_LATIOS,
    FLAG_MET_SCOTT_ON_SS_TIDAL,
    FLAG_DEFEATED_HO_OH,
    FLAG_DEFEATED_LUGIA,
    FLAG_HIDDEN_ITEMS_START,
    FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG,
    FLAG_HIDE_SAFARI_ZONE_SOUTH_CONSTRUCTION_WORKERS,
    FLAG_HIDE_ROUTE_101_BIRCH_ZIGZAGOON_BATTLE,
    FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_BIRCH,
    FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_BEDROOM,
    FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_INVISIBLE_NINJA_BOY,
    FLAG_HIDE_LILYCOVE_FAN_CLUB_INTERVIEWER,
    FLAG_HIDE_PLAYERS_HOUSE_DAD,
    FLAG_HIDE_ROUTE_104_MR_BRINEY,
    FLAG_HIDE_BRINEYS_HOUSE_MR_BRINEY,
    FLAG_HIDE_MR_BRINEY_DEWFORD_TOWN,
    FLAG_HIDE_ROUTE_109_MR_BRINEY,
    FLAG_HIDE_ROUTE_104_MR_BRINEY_BOAT,
    FLAG_HIDE_MR_BRINEY_BOAT_DEWFORD_TOWN,
    FLAG_HIDE_ROUTE_109_MR_BRINEY_BOAT,
    FLAG_HIDE_SAFARI_ZONE_SOUTH_EAST_EXPANSION,
    FLAG_HIDE_VICTORY_ROAD_EXIT_WALLY,
    FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_BEDROOM,
    FLAG_HIDE_PETALBURG_GYM_GREETER,
    FLAG_HIDE_FANCLUB_OLD_LADY,
    FLAG_HIDE_FANCLUB_BOY,
    FLAG_HIDE_FANCLUB_LITTLE_BOY,
    FLAG_HIDE_FANCLUB_LADY,
    FLAG_HIDE_VICTORY_ROAD_ENTRANCE_WALLY,
    FLAG_HIDE_SLATEPORT_CITY_HARBOR_SS_TIDAL,
    FLAG_HIDE_LILYCOVE_HARBOR_SSTIDAL,
    FLAG_HIDE_SLATEPORT_CITY_STERNS_SHIPYARD_MR_BRINEY,
    FLAG_HIDE_BRINEYS_HOUSE_PEEKO,
    FLAG_HIDE_ROUTE_116_MR_BRINEY,
    FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_UNKNOWN_0,
    FLAG_HIDE_ROUTE_101_BIRCH,
    FLAG_HIDE_ROUTE_103_BIRCH,
    FLAG_HIDE_LILYCOVE_MOTEL_GAME_DESIGNERS,
    FLAG_HIDE_SS_TIDAL_CORRIDOR_MR_BRINEY,
    FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_BELDUM_POKEBALL,
    FLAG_HIDE_LILYCOVE_CITY_RIVAL,
    FLAG_DEFEATED_RUSTBORO_GYM,
    FLAG_DEFEATED_ELITE_4_SIDNEY,
    FLAG_DEFEATED_ELITE_4_PHOEBE,
    FLAG_DEFEATED_ELITE_4_GLACIA,
    FLAG_DEFEATED_ELITE_4_DRAKE,
    FLAG_BADGE01_GET,
    FLAG_BADGE02_GET,
    FLAG_BADGE03_GET,
    FLAG_BADGE04_GET,
    FLAG_BADGE05_GET,
    FLAG_BADGE06_GET,
    FLAG_BADGE07_GET,
    FLAG_BADGE08_GET,
    FLAG_IS_CHAMPION,
    FLAG_ENABLE_SHIP_SOUTHERN_ISLAND,
    FLAG_DEOXYS_ROCK_COMPLETE,
    FLAG_ENABLE_SHIP_FARAWAY_ISLAND,
    FLAG_RECEIVED_POKEDEX_FROM_BIRCH,
    BANDERAS_GUION_FIN,
};

// Estado del sistema y del jugador.
enum BanderasSistema
{
    FLAG_SYS_POKEMON_GET = BANDERAS_GUION_FIN,
    FLAG_SYS_EXP_SHARE,
    FLAG_SYS_POKEDEX_GET,
    FLAG_SYS_GAME_CLEAR,
    FLAG_SYS_CHAT_USED,
    FLAG_SYS_USE_FLASH,
    FLAG_SYS_USE_STRENGTH,
    FLAG_SYS_CYCLING_ROAD,
    FLAG_SYS_CRUISE_MODE,
    FLAG_SYS_CLOCK_SET,
    FLAG_SYS_SHOAL_TIDE,
    FLAG_SYS_RIBBON_GET,
    FLAG_SYS_PC_LANETTE,
    FLAG_SYS_ENC_UP_ITEM,
    FLAG_SYS_ENC_DOWN_ITEM,
    FLAG_SYS_TV_LATIAS_LATIOS,
    FLAG_SYS_SHOAL_ITEM,
    FLAG_SYS_B_DASH,
    FLAG_SYS_CTRL_OBJ_DELETE,
    FLAG_SYS_RESET_RTC_ENABLE,
    BANDERAS_SISTEMA_FIN,
};

// Las ocho medallas. No gobiernan la obediencia -ese mecanismo ya no existe en este
// proyecto-; lo que dependen de ellas es cuanto dinero se pierde al quedar fuera de
// combate, el contador de la pantalla de guardado y el del menu principal.
#define NUM_BADGES         (1 + FLAG_BADGE08_GET - FLAG_BADGE01_GET)

// Se borran al cambiar el dia, asi que van al final: el borrado es un memset de un
// rango contiguo. Ahora mismo no hay ninguna; los eventos diarios que anadas van aqui.
enum BanderasDiarias
{
    DAILY_FLAGS_START = BANDERAS_SISTEMA_FIN,
    BANDERAS_DIARIAS_FIN = DAILY_FLAGS_START,
};

#define SYSTEM_FLAGS       BANDERAS_GUION_FIN
#define NUM_DAILY_FLAGS    (BANDERAS_DIARIAS_FIN - DAILY_FLAGS_START)
#define FLAGS_COUNT        BANDERAS_DIARIAS_FIN

// Estas NO van al guardado: viven en EWRAM (sSpecialFlags) y se pierden al salir.
#define SPECIAL_FLAGS_START 0x4000

enum BanderasEspeciales
{
    FLAG_HIDE_MAP_NAME_POPUP = SPECIAL_FLAGS_START,
    FLAG_DONT_TRANSITION_MUSIC,
    FLAG_SAFE_FOLLOWER_MOVEMENT,
    SPECIAL_FLAGS_END,
};

#define NUM_SPECIAL_FLAGS  (SPECIAL_FLAGS_END - SPECIAL_FLAGS_START)

#endif // GUARD_CONSTANTS_FLAGS_H
