#ifndef GUARD_CONSTANTS_MAP_TYPES_H
#define GUARD_CONSTANTS_MAP_TYPES_H

enum MapTypes
{
    MAP_TYPE_NONE,
    MAP_TYPE_TOWN,
    MAP_TYPE_CITY,
    MAP_TYPE_ROUTE,
    MAP_TYPE_UNDERGROUND,
    MAP_TYPE_UNDERWATER,
    MAP_TYPE_OCEAN_ROUTE,
    MAP_TYPE_INDOOR,
};

enum BattleBackgrounds
{
    BATTLE_BACKGROUND_NORMAL,
    BATTLE_BACKGROUND_GYM,
    BATTLE_BACKGROUND_MAGMA,
    BATTLE_BACKGROUND_AQUA,
    BATTLE_BACKGROUND_SIDNEY,
    BATTLE_BACKGROUND_PHOEBE,
    BATTLE_BACKGROUND_GLACIA,
    BATTLE_BACKGROUND_DRAKE,
    BATTLE_BACKGROUND_LEADER,
    BATTLE_BACKGROUND_WALLACE,
    BATTLE_BACKGROUND_GROUDON,
    BATTLE_BACKGROUND_KYOGRE,
    BATTLE_BACKGROUND_RAYQUAZA,
};

#endif  // GUARD_CONSTANTS_MAP_TYPES_H
