#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

enum Entrenadores
{
	TRAINER_NONE,
	TRAINER_CYNTHIA,
	TRAINER_LANCE,

	TRAINERS_COUNT
};

#endif  // GUARD_CONSTANTS_OPPONENTS_H
