#ifndef GUARD_CONSTANTS_POKEMON_SALVAJES_OW_H
#define GUARD_CONSTANTS_POKEMON_SALVAJES_OW_H

enum EstadosPokemonSalvajes
{
    ESTADO_POKEMON_SALVAJE_INACTIVO,
    ESTADO_POKEMON_SALVAJE_ACTIVO
};

#define MAXIMO_POKEMON_SALVAJES_OW                  4

#define FRECUENCIA_APARICION_POKEMON_SALVAJES_OW    80

#define DISTANCIA_MINIMA_POKEMON_SALVAJE_OW         3

#define VISIBILIDAD_POKEMON_SALVAJE_OW              8

#endif // GUARD_CONSTANTS_POKEMON_SALVAJES_OW_H
