#ifndef GUARD_SCRIPT_MENU_CONSTANTS_H
#define GUARD_SCRIPT_MENU_CONSTANTS_H

#define MULTICHOICE(name) {name, ARRAY_COUNT(name)}

#define MAX_MULTICHOICE_WIDTH 28

#define MULTI_B_PRESSED  127

enum Multiopciones
{
    MULTI_SI_NO_INFO,
    MULTI_BERRY_PLOT,
};

enum StdString
{
    STDSTRING_COOL,
    STDSTRING_BEAUTY,
    STDSTRING_CUTE,
    STDSTRING_SMART,
    STDSTRING_TOUGH,
    STDSTRING_NORMAL,
    STDSTRING_SUPER,
    STDSTRING_HYPER,
    STDSTRING_MASTER,
    STDSTRING_COOL2,
    STDSTRING_BEAUTY2,
    STDSTRING_CUTE2,
    STDSTRING_SMART2,
    STDSTRING_TOUGH2,
    STDSTRING_ITEMS,
    STDSTRING_KEYITEMS,
    STDSTRING_POKEBALLS,
    STDSTRING_TMHMS,
    STDSTRING_BERRIES,
    STDSTRING_SINGLE,
    STDSTRING_DOUBLE,
    STDSTRING_MULTI,
};

// Dynamic Multichoice Callbacks

#define DYN_MULTICHOICE_CB_SHOW_ITEM  1
#define DYN_MULTICHOICE_CB_NONE       255

#endif //GUARD_SCRIPT_MENU_CONSTANTS_H
