#ifndef GUARD_CONSTANTS_SOUND_H
#define GUARD_CONSTANTS_SOUND_H

enum Fanfares
{
    FANFARE_LEVEL_UP,
    FANFARE_HEAL,
    FANFARE_OBTAIN_BADGE,
    FANFARE_OBTAIN_ITEM,
    FANFARE_EVOLVED,
    FANFARE_OBTAIN_TMHM,
    FANFARE_EVOLUTION_INTRO,
    FANFARE_MOVE_DELETED,
    FANFARE_OBTAIN_BERRY,
    FANFARE_AWAKEN_LEGEND,
    FANFARE_SLOTS_JACKPOT,
    FANFARE_SLOTS_WIN,
    FANFARE_TOO_BAD,
    FANFARE_RG_JIGGLYPUFF,
    FANFARE_RG_DEX_RATING,
    FANFARE_RG_OBTAIN_KEY_ITEM,
    FANFARE_RG_CAUGHT_INTRO,
    FANFARE_RG_PHOTO,
    FANFARE_RG_POKE_FLUTE,
    FANFARE_OBTAIN_B_POINTS,
    FANFARE_REGISTER_MATCH_CALL,
    FANFARE_OBTAIN_SYMBOL,
    FANFARE_DP_TV_END,
    FANFARE_DP_OBTAIN_ITEM,
    FANFARE_DP_HEAL,
    FANFARE_DP_OBTAIN_KEY_ITEM,
    FANFARE_DP_OBTAIN_TMHM,
    FANFARE_DP_OBTAIN_BADGE,
    FANFARE_DP_LEVEL_UP,
    FANFARE_DP_OBTAIN_BERRY,
    FANFARE_DP_PARTNER,
    FANFARE_DP_EVOLVED,
    FANFARE_DP_POKETCH,
    FANFARE_DP_MOVE_DELETED,
    FANFARE_DP_ACCESSORY,
    FANFARE_PL_TV_END,
    FANFARE_PL_CLEAR_MINIGAME,
    FANFARE_PL_OBTAIN_ARCADE_POINTS,
    FANFARE_PL_OBTAIN_CASTLE_POINTS,
    FANFARE_PL_OBTAIN_B_POINTS,
    FANFARE_HG_OBTAIN_KEY_ITEM,
    FANFARE_HG_LEVEL_UP,
    FANFARE_HG_HEAL,
    FANFARE_HG_DEX_RATING_1,
    FANFARE_HG_DEX_RATING_2,
    FANFARE_HG_DEX_RATING_3,
    FANFARE_HG_DEX_RATING_4,
    FANFARE_HG_DEX_RATING_5,
    FANFARE_HG_DEX_RATING_6,
    FANFARE_HG_RECEIVE_EGG,
    FANFARE_HG_OBTAIN_ITEM,
    FANFARE_HG_EVOLVED,
    FANFARE_HG_OBTAIN_BADGE,
    FANFARE_HG_OBTAIN_TMHM,
    FANFARE_HG_VOLTORB_FLIP_1,
    FANFARE_HG_VOLTORB_FLIP_2,
    FANFARE_HG_ACCESSORY,
    FANFARE_HG_REGISTER_POKEGEAR,
    FANFARE_HG_OBTAIN_BERRY,
    FANFARE_HG_RECEIVE_POKEMON,
    FANFARE_HG_MOVE_DELETED,
    FANFARE_HG_THIRD_PLACE,
    FANFARE_HG_SECOND_PLACE,
    FANFARE_HG_FIRST_PLACE,
    FANFARE_HG_POKEATHLON_NEW,
    FANFARE_HG_WINNING_POKEATHLON,
    FANFARE_HG_OBTAIN_B_POINTS,
    FANFARE_HG_OBTAIN_ARCADE_POINTS,
    FANFARE_HG_OBTAIN_CASTLE_POINTS,
    FANFARE_HG_CLEAR_MINIGAME,
    FANFARE_HG_PARTNER
};

#define CRY_MODE_NORMAL        0 // Default
#define CRY_MODE_DOUBLES       1 // Shortened cry for double battles
#define CRY_MODE_ENCOUNTER     2 // Used when starting a static encounter, or when a Pokémon is "aggressive"
#define CRY_MODE_HIGH_PITCH    3 // Highest pitch mode, used exclusively by the move Howl
#define CRY_MODE_ECHO_START    4 // For 1st half of cry used by the move Hyper Voice. Played in reverse
#define CRY_MODE_FAINT         5 // Used when a Pokémon faints
#define CRY_MODE_ECHO_END      6 // For 2nd half of cry used by the move Hyper Voice
#define CRY_MODE_ROAR_1        7 // For 1st cry used by the move Roar
#define CRY_MODE_ROAR_2        8 // For 2nd cry used by the move Roar
#define CRY_MODE_GROWL_1       9 // For 1st cry used by the move Growl. Played in reverse
#define CRY_MODE_GROWL_2      10 // For 2nd cry used by the move Growl
#define CRY_MODE_WEAK         11 // Used when a Pokémon is unhealthy
#define CRY_MODE_WEAK_DOUBLES 12 // Equivalent to CRY_MODE_DOUBLES for CRY_MODE_WEAK

#define CRY_PRIORITY_NORMAL 10
#define CRY_PRIORITY_AMBIENT 1

#define CRY_VOLUME                  120

#define VELOCIDAD_ACELERADA_MUSICA  2
#define VELOCIDAD_LENTA_MUSICA      4

#endif // GUARD_CONSTANTS_SOUND_H
