#ifndef GUARD_TRAINERS_H
#define GUARD_TRAINERS_H

#include "constants/opponents.h"

enum TrainerPics
{
    TRAINER_PIC_BRENDAN,
    TRAINER_PIC_MAY,
    TRAINER_PIC_MAGMA_LEADER_MAXIE,
    TRAINER_PIC_CYNTHIA,
    TRAINER_PIC_LANCE,

    TRAINER_PIC_COUNT
};

enum TrainerBackPics
{
    TRAINER_BACK_PIC_ETHAN,
    TRAINER_BACK_PIC_BRENDAN,
    TRAINER_BACK_PIC_MAY,
};

enum TrainerClasses
{
    TRAINER_CLASS_HIKER,
    TRAINER_CLASS_TEAM_AQUA,
    TRAINER_CLASS_PKMN_BREEDER,
    TRAINER_CLASS_COOLTRAINER,
    TRAINER_CLASS_BIRD_KEEPER,
    TRAINER_CLASS_COLLECTOR,
    TRAINER_CLASS_SWIMMER_M,
    TRAINER_CLASS_TEAM_MAGMA,
    TRAINER_CLASS_EXPERT,
    TRAINER_CLASS_AQUA_ADMIN,
    TRAINER_CLASS_BLACK_BELT,
    TRAINER_CLASS_AQUA_LEADER,
    TRAINER_CLASS_HEX_MANIAC,
    TRAINER_CLASS_AROMA_LADY,
    TRAINER_CLASS_RUIN_MANIAC,
    TRAINER_CLASS_INTERVIEWER,
    TRAINER_CLASS_TUBER_F,
    TRAINER_CLASS_TUBER_M,
    TRAINER_CLASS_LADY,
    TRAINER_CLASS_BEAUTY,
    TRAINER_CLASS_RICH_BOY,
    TRAINER_CLASS_POKEMANIAC,
    TRAINER_CLASS_GUITARIST,
    TRAINER_CLASS_KINDLER,
    TRAINER_CLASS_CAMPER,
    TRAINER_CLASS_PICNICKER,
    TRAINER_CLASS_BUG_MANIAC,
    TRAINER_CLASS_PSYCHIC,
    TRAINER_CLASS_GENTLEMAN,
    TRAINER_CLASS_ELITE_FOUR,
    TRAINER_CLASS_LEADER,
    TRAINER_CLASS_SCHOOL_KID,
    TRAINER_CLASS_SR_AND_JR,
    TRAINER_CLASS_WINSTRATE,
    TRAINER_CLASS_POKEFAN,
    TRAINER_CLASS_YOUNGSTER,
    TRAINER_CLASS_CHAMPION,
    TRAINER_CLASS_FISHERMAN,
    TRAINER_CLASS_TRIATHLETE,
    TRAINER_CLASS_DRAGON_TAMER,
    TRAINER_CLASS_NINJA_BOY,
    TRAINER_CLASS_BATTLE_GIRL,
    TRAINER_CLASS_PARASOL_LADY,
    TRAINER_CLASS_SWIMMER_F,
    TRAINER_CLASS_TWINS,
    TRAINER_CLASS_SAILOR,
    TRAINER_CLASS_MAGMA_ADMIN,
    TRAINER_CLASS_RIVAL,
    TRAINER_CLASS_BUG_CATCHER,
    TRAINER_CLASS_PKMN_RANGER,
    TRAINER_CLASS_MAGMA_LEADER,
    TRAINER_CLASS_LASS,
    TRAINER_CLASS_YOUNG_COUPLE,
    TRAINER_CLASS_OLD_COUPLE,
    TRAINER_CLASS_SIS_AND_BRO,
    TRAINER_CLASS_RS_PROTAG,
    TRAINER_CLASS_COUNT,
};

enum TrainerEncounterMusic
{
    TRAINER_ENCOUNTER_MUSIC_NONE,
    TRAINER_ENCOUNTER_MUSIC_MALE, // standard male encounter music
    TRAINER_ENCOUNTER_MUSIC_FEMALE, // standard female encounter music
    TRAINER_ENCOUNTER_MUSIC_GIRL, // used for male Tubers and Young Couples too
    TRAINER_ENCOUNTER_MUSIC_SUSPICIOUS,
    TRAINER_ENCOUNTER_MUSIC_INTENSE,
    TRAINER_ENCOUNTER_MUSIC_COOL,
    TRAINER_ENCOUNTER_MUSIC_AQUA,
    TRAINER_ENCOUNTER_MUSIC_MAGMA,
    TRAINER_ENCOUNTER_MUSIC_SWIMMER,
    TRAINER_ENCOUNTER_MUSIC_TWINS, // used for other trainer classes too
    TRAINER_ENCOUNTER_MUSIC_ELITE_FOUR,
    TRAINER_ENCOUNTER_MUSIC_HIKER, // used for other trainer classes too
    TRAINER_ENCOUNTER_MUSIC_INTERVIEWER,
    TRAINER_ENCOUNTER_MUSIC_RICH, // Rich Boys and Gentlemen
    TRAINER_ENCOUNTER_MUSIC_CYNTHIA,
    TRAINER_ENCOUNTER_MUSIC_LANCE,
};

enum GenerosPokemonEntrenadores
{
    TRAINER_MON_MALE = 1,
    TRAINER_MON_FEMALE,
    TRAINER_MON_RANDOM_GENDER
};

#define F_TRAINER_FEMALE (1 << 7)

#endif  // GUARD_TRAINERS_H
