gText_ObtainedTheItem::
	.string "¡Obtuviste {VAR_TEXTO_2}!$"

gText_PutItemInPocket::
	.string "{JUGADOR} put away the {VAR_TEXTO_2}\n"
	.string "in the {VAR_TEXTO_3} POCKET.$"

gText_PlayerFoundOneItem::
	.string "¡{JUGADOR} encontró {VAR_TEXTO_2}!$"

gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "The BAG is full…$"

gText_ObtainedTheItems::
	.string "Obtained {VAR_TEXTO_1} {VAR_TEXTO_2}!$"

gText_PlayerFoundItems::
	.string "{JUGADOR} found {VAR_TEXTO_1} {VAR_TEXTO_2}!$"
