gText_ObtainedTheItem::
	.string "¡Obtuviste {VAR_TEXTO_2}!$"

gText_TheBagIsFull::
	.string "The BAG is full…$"

gText_PutItemInPocket::
	.string "{JUGADOR} put away the {VAR_TEXTO_2}\n"
	.string "in the {VAR_TEXTO_3} POCKET.$"

gText_PlayerFoundOneItem::
	.string "¡{JUGADOR} encontró {VAR_TEXTO_2}!$"

gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "The BAG is full…$"

gText_PlayerPutItemInBag::
	.string "{JUGADOR} put away the {VAR_TEXTO_2}\n"
	.string "in the BAG.$"

gText_ObtainedTheDecor::
	.string "Obtained the {VAR_TEXTO_2}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {VAR_TEXTO_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {VAR_TEXTO_2} was transferred\n"
	.string "to the PC.$"

gText_ObtainedTheItems::
	.string "Obtained {VAR_TEXTO_1} {VAR_TEXTO_2}!$"

gText_PlayerFoundItems::
	.string "{JUGADOR} found {VAR_TEXTO_1} {VAR_TEXTO_2}!$"
